spring:
  application:
    name: AppFellas Flight API
  data:
    mongodb:
      uri: mongodb://localhost:27017
      # If you want to run the app you need to replace the uri field with your local or cloud server url.
        # Example : uri: mongodb://username:password@192.168.1.88:27018
          # or
            # mongodb+srv://Ahmetyalcinkya:<db_password>@administration.kyuby.mongodb.net/?retryWrites=true&w=majority&appName=appFellasDb
              # You can change the database name.
      database: appFellasDb
server:
  port: 8080
  servlet:
    context-path: /AppFellas/api/v1
app:
  security:
    jwt:
      issuer: Ahmetyalcinkya
      secret: SMvaRsPuA4q2UnCmFtGxXEVQJbfrk3Z7D5j9y6TpB8eLNWhd
      expiration-in-minutes: 1440 # 1 Day