spring:
  application:
    name: AppFellas Flight API
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: appFellasDb
server:
  port: 8080
  servlet:
    context-path: /AppFellas/api/v1